### ISSUE TITLE
Merge when pipeline succeeds overridden when multiple commits are present

### ISSUE THREAD

**Issue by simPod** [Dazix/Gitlab-MR-summary#17]
Typically there's button like this to schedule merge
![image](https://user-images.githubusercontent.com/327717/84354155-acd60880-abc0-11ea-8e09-c4f8a7db3ef1.png)

However, the extension overrides it when multiple commits are in the PR so now I'm not sure whether the button schedules the merge after pipeline succeeds or whether it force-merges the PR

<img width="582" alt="Screenshot 2020-06-11 at 08 49 15" src="https://user-images.githubusercontent.com/327717/84354064-8912c280-abc0-11ea-88ee-5e92372489cc.png">

**Comment by Dazix** [comment]
Hi, thanks for report. It's fixed and new version is available on chrome webstore/mozilla addons page

**Comment by simPod** [comment]
Thanks, appreciated!
