### ISSUE TITLE
Remove "check delete branch" option

### ISSUE THREAD

**Issue by simPod** [Dazix/Gitlab-MR-summary#25]
This option is now redundant 

![image](https://user-images.githubusercontent.com/327717/97992909-abadae00-1de3-11eb-9952-77e7424ac41f.png)

as gitlab contains it by default

![image](https://user-images.githubusercontent.com/327717/97992880-9f295580-1de3-11eb-9b1f-3f92d393d652.png)

**Comment by Dazix** [comment]
Hi,
yes it's true, but not completely, this option gives you ability set this behavior on user level not only on project level. For example it's useful when you create mergerequest to project owned by another team with different flow/settings and you still want clean after yourself. So I think there is still usage for this option.

**Comment by simPod** [comment]
That makes sense 👍
